export type Gender = "men" | "women";

export type Product = {
  id: number;
  name: string;
  description: string;
  price: number;
  oldPrice?: number;
  category: "shoes" | "pants";
  categoryLabel: string;
  gender: Gender;
  genderLabel: string;
  brand: string;
  image: string;
  badge?: string;
  sizes?: string[];
  rating: number;
  reviewCount: number;
  salesCount: number;
  createdAt: string;
};

export const products: Product[] = [
  {
    id: 1,
    name: "Nova Air",
    description: "سنيكرز جلد ناعم للراحة اليومية",
    price: 599,
    oldPrice: 715,
    category: "shoes",
    categoryLabel: "أحذية",
    gender: "men",
    genderLabel: "رجالي",
    brand: "Nova",
    image: "/product-sneaker.png",
    badge: "الأكثر مبيعاً",
    sizes: ["40", "41", "42", "43", "44"],
    rating: 4.9,
    reviewCount: 128,
    salesCount: 340,
    createdAt: "2026-09-10",
  },
  {
    id: 2,
    name: "Heritage Loafer",
    description: "حذاء لوفر جلد بلمسة كلاسيكية",
    price: 799,
    oldPrice: 999,
    category: "shoes",
    categoryLabel: "أحذية",
    gender: "men",
    genderLabel: "رجالي",
    brand: "Heritage",
    image: "/product-loafer.png",
    badge: "خصم 20%",
    sizes: ["40", "41", "42", "43"],
    rating: 4.7,
    reviewCount: 86,
    salesCount: 214,
    createdAt: "2026-08-27",
  },
  {
    id: 3,
    name: "Denim 01",
    description: "جينز إنديغو بقصة Slim مريحة",
    price: 499,
    category: "pants",
    categoryLabel: "بنطلونات",
    gender: "men",
    genderLabel: "رجالي",
    brand: "Urban Form",
    image: "/product-jeans.png",
    badge: "جديد",
    sizes: ["30", "32", "34", "36"],
    rating: 4.8,
    reviewCount: 72,
    salesCount: 176,
    createdAt: "2026-09-18",
  },
  {
    id: 4,
    name: "Run Lite",
    description: "خفة ومرونة لكل خطوة في يومك",
    price: 699,
    category: "shoes",
    categoryLabel: "أحذية",
    gender: "women",
    genderLabel: "حريمي",
    brand: "Nova",
    image: "/product-sneaker.png",
    sizes: ["37", "38", "39", "40", "41"],
    rating: 4.9,
    reviewCount: 94,
    salesCount: 198,
    createdAt: "2026-09-15",
  },
  {
    id: 5,
    name: "Chino Sand",
    description: "بنطلون شينو بلون رملي متعدد الإطلالات",
    price: 549,
    oldPrice: 649,
    category: "pants",
    categoryLabel: "بنطلونات",
    gender: "men",
    genderLabel: "رجالي",
    brand: "Urban Form",
    image: "/product-jeans.png",
    badge: "خصم 15%",
    sizes: ["30", "32", "34", "36"],
    rating: 4.6,
    reviewCount: 51,
    salesCount: 143,
    createdAt: "2026-08-12",
  },
  {
    id: 6,
    name: "Oxford 02",
    description: "أناقة رسمية بخامة جلد متينة",
    price: 999,
    category: "shoes",
    categoryLabel: "أحذية",
    gender: "men",
    genderLabel: "رجالي",
    brand: "Heritage",
    image: "/product-loafer.png",
    sizes: ["40", "41", "42", "43"],
    rating: 4.5,
    reviewCount: 38,
    salesCount: 97,
    createdAt: "2026-07-29",
  },
  {
    id: 7,
    name: "City Cargo",
    description: "كارجو عملي بتفاصيل عصرية",
    price: 579,
    category: "pants",
    categoryLabel: "بنطلونات",
    gender: "women",
    genderLabel: "حريمي",
    brand: "Linea",
    image: "/product-jeans.png",
    badge: "جديد",
    sizes: ["28", "30", "32", "34"],
    rating: 4.7,
    reviewCount: 47,
    salesCount: 121,
    createdAt: "2026-09-20",
  },
  {
    id: 8,
    name: "Weekend Court",
    description: "سنيكرز يومي بخطوط نظيفة",
    price: 629,
    category: "shoes",
    categoryLabel: "أحذية",
    gender: "women",
    genderLabel: "حريمي",
    brand: "Nova",
    image: "/product-sneaker.png",
    sizes: ["37", "38", "39", "40", "41"],
    rating: 4.4,
    reviewCount: 29,
    salesCount: 83,
    createdAt: "2026-07-15",
  },
  {
    id: 9,
    name: "Studio Straight",
    description: "بنطلون بقصة مستقيمة وحضور هادئ",
    price: 529,
    category: "pants",
    categoryLabel: "بنطلونات",
    gender: "women",
    genderLabel: "حريمي",
    brand: "Linea",
    image: "/product-jeans.png",
    sizes: ["28", "30", "32", "34"],
    rating: 4.8,
    reviewCount: 63,
    salesCount: 112,
    createdAt: "2026-09-05",
  },
  {
    id: 10,
    name: "City Derby",
    description: "حذاء رسمي خفيف للمشاوير المهمة",
    price: 899,
    oldPrice: 1_049,
    category: "shoes",
    categoryLabel: "أحذية",
    gender: "men",
    genderLabel: "رجالي",
    brand: "Maison 24",
    image: "/product-loafer.png",
    badge: "خصم 14%",
    sizes: ["40", "41", "42", "43"],
    rating: 4.3,
    reviewCount: 24,
    salesCount: 68,
    createdAt: "2026-06-30",
  },
];

export function formatPrice(price: number) {
  return new Intl.NumberFormat("ar-EG").format(price);
}
