import Image from "next/image";
import Link from "next/link";

export default function AboutUs() {
  return (
    <main>
      <section className="inner-hero"><div className="site-container"><span className="eyebrow">الحكاية وراء الاختيار</span><h1>نختار لك ما<br />نختاره لأنفسنا.</h1><p>Nova Store مساحة بسيطة للقطع التي تعيش معك، لا مجرد أشياء تملأ خزانتك.</p></div></section>
      <section className="story-section"><div className="site-container"><div className="story-grid"><div className="story-copy"><span className="eyebrow">قصتنا</span><h2>أقل، لكن أفضل.</h2><p>بدأت Nova Store من سؤال بسيط: لماذا يصعب العثور على الأساسيات التي تجمع بين الشكل المميز والراحة والسعر العادل؟ لذلك بنينا متجراً يركز على ما يهم فعلاً — جودة تلمسها، قصّات تعيش، وتجربة شراء تشعرك بالثقة.</p><div className="story-points"><div className="story-point"><span className="story-point-number">01</span><div><strong>نختار ببطء</strong><span>لا نطارد كل ترند. نضيف القطعة عندما تستحق.</span></div></div><div className="story-point"><span className="story-point-number">02</span><div><strong>نسمع لك</strong><span>ملاحظاتك هي ما يجعل المجموعة القادمة أفضل.</span></div></div></div></div><div className="story-image"><Image src="/hero-editorial.png" alt="اختيارات من Nova Store" fill sizes="(max-width: 680px) 90vw, 45vw" /></div></div></div></section>
      <section className="section section-white"><div className="site-container"><div className="section-heading"><div><span className="eyebrow">ما نؤمن به</span><h2>قيم بسيطة،<br />في كل تفصيلة.</h2></div><p>من طريقة اختيار المنتج إلى لحظة وصوله لبابك، نريد أن تكون التجربة واضحة ومريحة.</p></div><div className="review-grid" style={{ color: "var(--ink)" }}><div className="summary-card"><span className="story-point-number">01</span><h3>الجودة أولاً</h3><p>نبحث عن الخامة المريحة والتفاصيل التي تبقى جميلة مع الوقت.</p></div><div className="summary-card"><span className="story-point-number">02</span><h3>وضوح كامل</h3><p>صور وأسعار ومعلومات مباشرة، من غير مبالغة أو مفاجآت.</p></div><div className="summary-card"><span className="story-point-number">03</span><h3>خدمة إنسانية</h3><p>نحن هنا لنساعدك في المقاس والاختيار وبعد وصول الطلب أيضاً.</p></div></div><div style={{ textAlign: "center", marginTop: "45px" }}><Link href="/products" className="button button-primary">تصفح اختياراتنا <span className="button-arrow">←</span></Link></div></div></section>
    </main>
  );
}
